### PR TITLE
Response formatter

### PR DESCRIPTION
**Pull request by Leohemmingsson**
Added option to give response_formatter, if given the function will call the response_formatter with the arguments provided in the return or the error message from the fields function as normal function args. 

Example in README.md

### CODE REVIEW

**Review by ivajon — COMMENTED** [review]
In general, it looks good, please add 2 more commits,
1 removing __pycache__ folder, 1 for adding __pycache__/* to .gitignore

**Comment by Leohemmingsson** [comment]
Fixed the changes

**Review by ivajon — APPROVED** [review]
Looks good now

**Comment by ivajon** [comment]
Looks good

**Pull request merged**
